# Generated by Django 4.1.7 on 2023-04-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0002_remove_booking_hotel_remove_room_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата проверки'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оформления'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.guest', verbose_name='Гость'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_checkout',
            field=models.BooleanField(default=True, verbose_name='Проверено'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_of_guest',
            field=models.IntegerField(default=1, verbose_name='Кол-во гостей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='age',
            field=models.IntegerField(default=20, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.CharField(max_length=30, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=20, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Есть в книге?'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(default=1000.0, verbose_name='Цена'),
        ),
    ]
