# Generated by Django 4.1.7 on 2023-05-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0003_alter_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_img', models.ImageField(upload_to='static/images')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.BooleanField(default=True, verbose_name='Доп.услуги'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата заселения'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выселения'),
        ),
    ]
