# Generated by Django 4.1.7 on 2023-05-04 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0006_remove_guest_email_guest_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ФИО')),
                ('age', models.DateField(max_length=8, verbose_name='Дата рождения')),
                ('passport', models.CharField(max_length=10, verbose_name='Паспортные данные')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('post', models.CharField(max_length=100, verbose_name='Должность')),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=11, verbose_name='День недели')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.staff', verbose_name='Сотрудник')),
            ],
        ),
    ]
