# Generated by Django 4.1.7 on 2023-05-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
