# Generated by Django 4.1.7 on 2023-05-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0009_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(default=1000.0, verbose_name='Цена')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Есть в книге?')),
                ('img', models.ImageField(upload_to='%Y/%m/%d/', verbose_name='Изображение')),
            ],
        ),
    ]
