# Generated by Django 3.2 on 2023-05-20 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0010_room2'),
    ]

    operations = [
        migrations.AddField(
            model_name='room2',
            name='hottest',
            field=models.BooleanField(default=False, verbose_name='Является горячим предложением'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.room2', verbose_name='Комната'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
