# Generated by Django 3.2 on 2023-05-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0011_auto_20230520_0433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room2',
            new_name='Room',
        ),
    ]
