# Generated by Django 4.1.7 on 2023-05-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0012_rename_room2_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='img',
            field=models.ImageField(default=1, upload_to='%Y/%m/%d/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=models.DateTimeField(max_length=8, verbose_name='Дата рождения'),
        ),
    ]
