# Generated by Django 4.1.7 on 2023-05-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0016_alter_staff_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='age',
            new_name='data',
        ),
    ]
