# Generated by Django 4.1.7 on 2023-05-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0017_rename_age_staff_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='data',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
