# Generated by Django 4.1.7 on 2023-05-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0018_alter_staff_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
    ]
