# Generated by Django 4.1.7 on 2023-06-14 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0020_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата заселения'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата выселения'),
        ),
    ]
