# Generated by Django 4.1.7 on 2023-06-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0023_alter_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_of_child',
            field=models.IntegerField(default=1, verbose_name='Кол-во детей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_of_guest',
            field=models.IntegerField(default=1, verbose_name='Кол-во взрослых'),
        ),
    ]
