# Generated by Django 4.1.7 on 2023-06-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0024_booking_num_of_child_alter_booking_num_of_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default=1, max_length=11, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
