# Generated by Django 4.1.7 on 2023-06-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0025_booking_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default=1, max_length=40, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
