# Generated by Django 5.0.3 on 2024-05-08 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0027_room_bath_room_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ожидание', 'Ожидание'), ('подтверждено', 'Подтверждено'), ('отменено', 'Отменено')], default='ожидание', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.room', verbose_name='Номер'),
        ),
    ]
