# Generated by Django 5.0.3 on 2024-06-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0029_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='date_subscribed',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
